### ISSUE TITLE
Weird metaphone results from pure python implementation

### ISSUE THREAD

**Issue by georgedorn** [jamesturk/jellyfish#85] opened 2017-08-07 23:37 UTC
On Python 2.7, on OS X, using Homebrew as package manager, I get this:
```
In [2]: jellyfish.metaphone(u'washington')
Out[2]: u'XNKTN'
```

On Python 2.7 on Ubuntu, I get this:
```
In [2]: jellyfish.metaphone(u'washington')
Out[2]: 'WXNKTN'
```

It's probably something to do with an underlying library, but I'm not sure how to debug this further.

Edit:  it appears to be using the pure Python implementation on OS X, due to this import error:
```
ImportError                               Traceback (most recent call last)
<ipython-input-3-597c8ebe8c25> in <module>()
----> 1 from jellyfish.cjellyfish import *

ImportError: dlopen(/Users/user/workspace/project/.virt/lib/python2.7/site-packages/jellyfish/cjellyfish.so, 2): Symbol not found: _PyUnicodeUCS2_AsUTF8String
  Referenced from: /Users/user/workspace/project/.virt/lib/python2.7/site-packages/jellyfish/cjellyfish.so
  Expected in: flat namespace
 in /Users/user/workspace/project/.virt/lib/python2.7/site-packages/jellyfish/cjellyfish.so
```

**Comment by jamesturk** [comment] 2017-08-08 00:30
Sorry, I can't reproduce this.  On OSX w/ Homebrew:

Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jellyfish
>>> jellyfish.metaphone(u'washington')
'WXNKTN'

**Comment by georgedorn** [comment] 2017-08-08 00:42
See above, I added more details.  It appears to be the pure Python
implementation, so if your build runs the cjellyfish implementation it will
work correctly.

**Comment by jamesturk** [comment] 2018-04-07 13:56
just cut a new release, closing this, feel free to re-open if it persists somehow

**Closed by jamesturk** 2018-04-07 13:56 UTC
